//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace clienteNet.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SensorSoap11Binding", Namespace="http://main")]
    public partial class Sensor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getVolumenOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesencriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveSensorOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarOperationCompleted;
        
        private System.Threading.SendOrPostCallback setLedOperationCompleted;
        
        private System.Threading.SendOrPostCallback setNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLedOperationCompleted;
        
        private System.Threading.SendOrPostCallback readSondaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sensor() {
            this.Url = global::clienteNet.Properties.Settings.Default.clienteNet_localhost_Sensor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getVolumenCompletedEventHandler getVolumenCompleted;
        
        /// <remarks/>
        public event DesencriptarCompletedEventHandler DesencriptarCompleted;
        
        /// <remarks/>
        public event getNombreCompletedEventHandler getNombreCompleted;
        
        /// <remarks/>
        public event saveSensorCompletedEventHandler saveSensorCompleted;
        
        /// <remarks/>
        public event saveLogCompletedEventHandler saveLogCompleted;
        
        /// <remarks/>
        public event consultarCompletedEventHandler consultarCompleted;
        
        /// <remarks/>
        public event setLedCompletedEventHandler setLedCompleted;
        
        /// <remarks/>
        public event setNombreCompletedEventHandler setNombreCompleted;
        
        /// <remarks/>
        public event getFechaCompletedEventHandler getFechaCompleted;
        
        /// <remarks/>
        public event getLedCompletedEventHandler getLedCompleted;
        
        /// <remarks/>
        public event readSondaCompletedEventHandler readSondaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getVolumen", RequestNamespace="http://main", ResponseNamespace="http://main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int getVolumen([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            object[] results = this.Invoke("getVolumen", new object[] {
                        usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getVolumenAsync(string usuario) {
            this.getVolumenAsync(usuario, null);
        }
        
        /// <remarks/>
        public void getVolumenAsync(string usuario, object userState) {
            if ((this.getVolumenOperationCompleted == null)) {
                this.getVolumenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVolumenOperationCompleted);
            }
            this.InvokeAsync("getVolumen", new object[] {
                        usuario}, this.getVolumenOperationCompleted, userState);
        }
        
        private void OngetVolumenOperationCompleted(object arg) {
            if ((this.getVolumenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVolumenCompleted(this, new getVolumenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Desencriptar", RequestNamespace="http://main", ResponseNamespace="http://main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string Desencriptar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string str) {
            object[] results = this.Invoke("Desencriptar", new object[] {
                        str});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesencriptarAsync(string str) {
            this.DesencriptarAsync(str, null);
        }
        
        /// <remarks/>
        public void DesencriptarAsync(string str, object userState) {
            if ((this.DesencriptarOperationCompleted == null)) {
                this.DesencriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesencriptarOperationCompleted);
            }
            this.InvokeAsync("Desencriptar", new object[] {
                        str}, this.DesencriptarOperationCompleted, userState);
        }
        
        private void OnDesencriptarOperationCompleted(object arg) {
            if ((this.DesencriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesencriptarCompleted(this, new DesencriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getNombre", RequestNamespace="http://main", ResponseNamespace="http://main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getNombre() {
            object[] results = this.Invoke("getNombre", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNombreAsync() {
            this.getNombreAsync(null);
        }
        
        /// <remarks/>
        public void getNombreAsync(object userState) {
            if ((this.getNombreOperationCompleted == null)) {
                this.getNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNombreOperationCompleted);
            }
            this.InvokeAsync("getNombre", new object[0], this.getNombreOperationCompleted, userState);
        }
        
        private void OngetNombreOperationCompleted(object arg) {
            if ((this.getNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNombreCompleted(this, new getNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:saveSensor", RequestNamespace="http://main", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void saveSensor() {
            this.Invoke("saveSensor", new object[0]);
        }
        
        /// <remarks/>
        public void saveSensorAsync() {
            this.saveSensorAsync(null);
        }
        
        /// <remarks/>
        public void saveSensorAsync(object userState) {
            if ((this.saveSensorOperationCompleted == null)) {
                this.saveSensorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveSensorOperationCompleted);
            }
            this.InvokeAsync("saveSensor", new object[0], this.saveSensorOperationCompleted, userState);
        }
        
        private void OnsaveSensorOperationCompleted(object arg) {
            if ((this.saveSensorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveSensorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:saveLog", RequestNamespace="http://main", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void saveLog([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string metodo) {
            this.Invoke("saveLog", new object[] {
                        usuario,
                        metodo});
        }
        
        /// <remarks/>
        public void saveLogAsync(string usuario, string metodo) {
            this.saveLogAsync(usuario, metodo, null);
        }
        
        /// <remarks/>
        public void saveLogAsync(string usuario, string metodo, object userState) {
            if ((this.saveLogOperationCompleted == null)) {
                this.saveLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveLogOperationCompleted);
            }
            this.InvokeAsync("saveLog", new object[] {
                        usuario,
                        metodo}, this.saveLogOperationCompleted, userState);
        }
        
        private void OnsaveLogOperationCompleted(object arg) {
            if ((this.saveLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:consultar", RequestNamespace="http://main", ResponseNamespace="http://main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string consultar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string str, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            object[] results = this.Invoke("consultar", new object[] {
                        str,
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAsync(string str, string usuario) {
            this.consultarAsync(str, usuario, null);
        }
        
        /// <remarks/>
        public void consultarAsync(string str, string usuario, object userState) {
            if ((this.consultarOperationCompleted == null)) {
                this.consultarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarOperationCompleted);
            }
            this.InvokeAsync("consultar", new object[] {
                        str,
                        usuario}, this.consultarOperationCompleted, userState);
        }
        
        private void OnconsultarOperationCompleted(object arg) {
            if ((this.consultarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCompleted(this, new consultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setLed", RequestNamespace="http://main", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setLed(int led, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            this.Invoke("setLed", new object[] {
                        led,
                        usuario});
        }
        
        /// <remarks/>
        public void setLedAsync(int led, string usuario) {
            this.setLedAsync(led, usuario, null);
        }
        
        /// <remarks/>
        public void setLedAsync(int led, string usuario, object userState) {
            if ((this.setLedOperationCompleted == null)) {
                this.setLedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetLedOperationCompleted);
            }
            this.InvokeAsync("setLed", new object[] {
                        led,
                        usuario}, this.setLedOperationCompleted, userState);
        }
        
        private void OnsetLedOperationCompleted(object arg) {
            if ((this.setLedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setLedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setNombre", RequestNamespace="http://main", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setNombre([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nombre) {
            this.Invoke("setNombre", new object[] {
                        nombre});
        }
        
        /// <remarks/>
        public void setNombreAsync(string nombre) {
            this.setNombreAsync(nombre, null);
        }
        
        /// <remarks/>
        public void setNombreAsync(string nombre, object userState) {
            if ((this.setNombreOperationCompleted == null)) {
                this.setNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetNombreOperationCompleted);
            }
            this.InvokeAsync("setNombre", new object[] {
                        nombre}, this.setNombreOperationCompleted, userState);
        }
        
        private void OnsetNombreOperationCompleted(object arg) {
            if ((this.setNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setNombreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getFecha", RequestNamespace="http://main", ResponseNamespace="http://main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getFecha([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            object[] results = this.Invoke("getFecha", new object[] {
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getFechaAsync(string usuario) {
            this.getFechaAsync(usuario, null);
        }
        
        /// <remarks/>
        public void getFechaAsync(string usuario, object userState) {
            if ((this.getFechaOperationCompleted == null)) {
                this.getFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFechaOperationCompleted);
            }
            this.InvokeAsync("getFecha", new object[] {
                        usuario}, this.getFechaOperationCompleted, userState);
        }
        
        private void OngetFechaOperationCompleted(object arg) {
            if ((this.getFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFechaCompleted(this, new getFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getLed", RequestNamespace="http://main", ResponseNamespace="http://main", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public int getLed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            object[] results = this.Invoke("getLed", new object[] {
                        usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getLedAsync(string usuario) {
            this.getLedAsync(usuario, null);
        }
        
        /// <remarks/>
        public void getLedAsync(string usuario, object userState) {
            if ((this.getLedOperationCompleted == null)) {
                this.getLedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLedOperationCompleted);
            }
            this.InvokeAsync("getLed", new object[] {
                        usuario}, this.getLedOperationCompleted, userState);
        }
        
        private void OngetLedOperationCompleted(object arg) {
            if ((this.getLedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLedCompleted(this, new getLedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:readSonda", RequestNamespace="http://main", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void readSonda() {
            this.Invoke("readSonda", new object[0]);
        }
        
        /// <remarks/>
        public void readSondaAsync() {
            this.readSondaAsync(null);
        }
        
        /// <remarks/>
        public void readSondaAsync(object userState) {
            if ((this.readSondaOperationCompleted == null)) {
                this.readSondaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadSondaOperationCompleted);
            }
            this.InvokeAsync("readSonda", new object[0], this.readSondaOperationCompleted, userState);
        }
        
        private void OnreadSondaOperationCompleted(object arg) {
            if ((this.readSondaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.readSondaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getVolumenCompletedEventHandler(object sender, getVolumenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVolumenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVolumenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DesencriptarCompletedEventHandler(object sender, DesencriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesencriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesencriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getNombreCompletedEventHandler(object sender, getNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void saveSensorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void saveLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void consultarCompletedEventHandler(object sender, consultarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setLedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setNombreCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getFechaCompletedEventHandler(object sender, getFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getLedCompletedEventHandler(object sender, getLedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void readSondaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591