export enum actionConsts {
    AUTHENTICATION_STATE_INITIALIZED = 'AUTHENTICATION_STATE_INITIALIZED',
    SPLASH_SCREEN_HIDDEN = 'SPLASH_SCREEN_HIDDEN',
    UPDATE_EMAIL = 'UPDATE_EMAIL',
    UPDATE_ERROR = 'UPDATE_ERROR',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    REQUEST_TOKEN_REQUESTED = 'REQUEST_TOKEN_REQUESTED',
    REQUEST_TOKEN_SUCCEEDED = 'REQUEST_TOKEN_SUCCEEDED',
    REQUEST_TOKEN_FAILED = 'REQUEST_TOKEN_FAILED',
    REQUEST_INVITATIONS_REQUESTED = 'REQUEST_INVITATIONS_REQUESTED',
    REQUEST_INVITATIONS_SUCCEEDED = 'REQUEST_INVITATIONS_SUCCEEDED',
    REQUEST_INVITATIONS_FAILED = 'REQUEST_INVITATIONS_FAILED',

    REQUEST_REGISTER_REQUESTED = 'REQUEST_REGISTER_REQUESTED',
    REQUEST_REGISTER_SUCCEEDED = 'REQUEST_REGISTER_SUCCEEDED',
    REQUEST_REGISTER_FAILED = 'REQUEST_REGISTER_FAILED',
    SIGNOUT = 'SIGNOUT',
    NAVIGATE = 'NAVIGATE',
    REQUEST_UPDATE_REQUESTED = 'REQUEST_UPDATE_REQUESTED',
    REQUEST_UPDATE_SUCCEEDED = 'REQUEST_UPDATE_SUCCEEDED',
    REQUEST_UPDATE_FAILED = 'REQUEST_UPDATE_FAILED',
    LOAD_BUSINESS_REQUESTED = 'LOAD_BUSINESS_REQUESTED',
    LOAD_BUSINESS_SUCCEEDED = 'LOAD_BUSINESS_SUCCEEDED',
    LOAD_BUSINESS_FAILED = 'LOAD_BUSINESS_FAILED',
    SPLASH_SCREEN_DISPLAYED = 'SPLASH_SCREEN_DISPLAYED',
    SET_APP_OUTDATED = 'SET_APP_OUTDATED',
    SET_API_VERSIONS = 'SET_API_VERSIONS',

    REQUEST_NAME_CHANGE_REQUESTED = 'REQUEST_NAME_CHANGE_REQUESTED',
    REQUEST_NAME_CHANGE_SUCCEEDED = 'REQUEST_NAME_CHANGE_SUCCEEDED',
    REQUEST_NAME_CHANGE_FAILED = 'REQUEST_NAME_CHANGE_FAILED',

    REQUEST_EMAIL_CHANGE_REQUESTED = 'REQUEST_EMAIL_CHANGE_REQUESTED',
    REQUEST_EMAIL_CHANGE_SUCCEEDED = 'REQUEST_EMAIL_CHANGE_SUCCEEDED',
    REQUEST_EMAIL_CHANGE_FAILED = 'REQUEST_EMAIL_CHANGE_FAILED',

    REQUEST_PHONE_CHANGE_REQUESTED = 'REQUEST_PHONE_CHANGE_REQUESTED',
    REQUEST_PHONE_CHANGE_SUCCEEDED = 'REQUEST_PHONE_CHANGE_SUCCEEDED',
    REQUEST_PHONE_CHANGE_FAILED = 'REQUEST_PHONE_CHANGE_FAILED',

    REQUEST_CONFIRM_USER_CODE_REQUESTED = 'REQUEST_CONFIRM_USER_CODE_REQUESTED',
    REQUEST_CONFIRM_USER_CODE_SUCCEEDED = 'REQUEST_CONFIRM_USER_CODE_SUCCEEDED',
    REQUEST_CONFIRM_USER_CODE_FAILED = 'REQUEST_CONFIRM_USER_CODE_FAILED',

    REQUEST_CONFIRM_EMAIL_CODE_REQUESTED = 'REQUEST_CONFIRM_EMAIL_CODE_REQUESTED',
    REQUEST_CONFIRM_EMAIL_CODE_SUCCEEDED = 'REQUEST_CONFIRM_EMAIL_CODE_SUCCEEDED',
    REQUEST_CONFIRM_EMAIL_CODE_FAILED = 'REQUEST_CONFIRM_EMAIL_CODE_FAILED',

    REQUEST_CONFIRM_PHONE_CODE_REQUESTED = 'REQUEST_CONFIRM_PHONE_CODE_REQUESTED',
    REQUEST_CONFIRM_PHONE_CODE_SUCCEEDED = 'REQUEST_CONFIRM_PHONE_CODE_SUCCEEDED',
    REQUEST_CONFIRM_PHONE_CODE_FAILED = 'REQUEST_CONFIRM_PHONE_CODE_FAILED',

    REQUEST_SEND_EMAIL_CODE_REQUESTED = 'REQUEST_SEND_EMAIL_CODE_REQUESTED',
    REQUEST_SEND_EMAIL_CODE_SUCCEEDED = 'REQUEST_SEND_EMAIL_CODE_SUCCEEDED',
    REQUEST_SEND_EMAIL_CODE_FAILED = 'REQUEST_SEND_EMAIL_CODE_FAILED',

    REQUEST_SEND_PHONE_CODE_REQUESTED = 'REQUEST_SEND_PHONE_CODE_REQUESTED',
    REQUEST_SEND_PHONE_CODE_SUCCEEDED = 'REQUEST_SEND_PHONE_CODE_SUCCEEDED',
    REQUEST_SEND_PHONE_CODE_FAILED =    'REQUEST_SEND_PHONE_CODE_FAILED',

    REQUEST_SEND_NEW_USER_CODE_REQUESTED = 'REQUEST_SEND_NEW_USER_CODE_REQUESTED',
    REQUEST_SEND_NEW_USER_CODE_SUCCEEDED = 'REQUEST_SEND_NEW_USER_CODE_SUCCEEDED',
    REQUEST_SEND_NEW_USER_CODE_FAILED = 'REQUEST_SEND_NEW_USER_CODE_FAILED',
    REQUEST_USER_DATA_FAILED = "REQUEST_USER_DATA_FAILED",
    HIDE_SPINNER = 'HIDE_SPINNER'
}