export enum NotificationTypes {
    NOTIFICATIONS_REQUESTED_OFF_SCREEN = "NOTIFICATIONS_REQUESTED_OFF_SCREEN",
    NOTIFICATIONS_SUCCEDED_OFF_SCREEN = "NOTIFICATIONS_SUCCEDED_OFF_SCREEN",
    NOTIFICATIONS_FAILED_OFF_SCREEN = "NOTIFICATIONS_FAILED_OFF_SCREEN",
    NOTIFICATIONS_REQUESTED_ON_SCREEN = "NOTIFICATIONS_REQUESTED_ON_SCREEN",
    NOTIFICATIONS_SUCCEDED_ON_SCREEN = "NOTIFICATIONS_SUCCEDED_ON_SCREEN",
    NOTIFICATIONS_FAILED_ON_SCREEN = "NOTIFICATIONS_FAILED_ON_SCREEN",
    MARK_NOTIFICATIONS_AS_READ = "MARK_NOTIFICATIONS_AS_READ",
    DELETE_OLD_NOTIFICATIONS = "DELETE_OLD_NOTIFICATIONS",
    UPDATE_FROM_STORAGE = "UPDATE_FROM_STORAGE",
    SWITCH_ON_SCREEN = "SWITCH_ON_SCREEN",
    SET_TIMER = "SET_TIMER",
    UNSET_TIMER = "UNSET_TIMER",
    PULL_NOTIFICATIONS = "PULL_NOTIFICATIONS",
    STARTED_LOADING_ON_BACKGROUND = "STARTED_LOADING_ON_BACKGROUND",
    FINISHED_LOADING_ON_BACKGROUND = "FINISHED_LOADING_ON_BACKGROUND",
    UPDATE_HUB_CONNECTION = "UPDATE_HUB_CONNECTION"
  }