// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.6.0.0
//      SpecFlow Generator Version:3.6.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KeTePongoServer.Spec.Features.V1_0
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("ConsumerUserRegistration", Description="       Consumer user registration scenarios", SourceFile="Features\\v1_0\\ConsumerUserRegistration.feature", SourceLine=0)]
    public partial class ConsumerUserRegistrationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "ConsumerUserRegistration.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/v1_0", "ConsumerUserRegistration", "       Consumer user registration scenarios", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation without refreshing token after consume" +
            "r data submitted", SourceLine=3)]
        public virtual void NewConsumerUserWithAnEmailInvitationWithoutRefreshingTokenAfterConsumerDataSubmitted()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation without refreshing token after consume" +
                    "r data submitted", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationWithoutRefreshingTokenAfterConsumerDataSubmitted@pcc" +
                        "om.es\' Password:\',Adios22\' Name:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
    testRunner.When(@"1_0 consumer data is submitted (TradeName:'El Bar NewConsumerUserWithAnEmailInvitationWithoutRefreshingTokenAfterConsumerDataSubmitted' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'(.*)')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table2.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationWithoutRefreshingTokenAfterConsum" +
                                "erDataSubmitted@pccom.es",
                            "Gon Navarro"});
                table2.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationWithoutRefreshingTokenAfterConsumer" +
                                "DataSubmitted@pccom.com",
                            "Pepe"});
                table2.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationWithoutRefreshingTokenAfterCon" +
                                "sumerDataSubmitted@pccom.es",
                            "Gonzalo Gallego"});
#line 8
    testRunner.And("1_0 send new consumer user invitation", ((string)(null)), table2, "And ");
#line hidden
#line 13
    testRunner.Then("1_0 response is Unauthorized", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation and cancel the linking", SourceLine=14)]
        public virtual void NewConsumerUserWithAnEmailInvitationAndCancelTheLinking()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation and cancel the linking", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationAndCancelTheLinking@pccom.es\' Password:\',Adios22\' Na" +
                        "me:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 17
    testRunner.And("1_0 consumer data is submitted (TradeName:\'El Bar NewConsumerUserWithAnEmailInvit" +
                        "ationAndCancelTheLinking\' Address:\'C\\Bajovento 3\' StateOrProvince:\'Alicante\' Tow" +
                        "n:\'Elche\' PostalCode:\'03203\' SanitaryMeasures:\'Medida 1, Medida 2\' Image:\'(.*)\')" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table3.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationAndCancelTheLinking@pccom.es",
                            "Gon Navarro"});
                table3.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationAndCancelTheLinking@pccom.com",
                            "Pepe"});
                table3.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationAndCancelTheLinking@pccom.es",
                            "Gonzalo Gallego"});
#line 21
    testRunner.And("1_0 send new consumer user invitation", ((string)(null)), table3, "And ");
#line hidden
#line 26
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
    testRunner.And("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
    testRunner.And("1_0 confirm user invitation to gonzalogallego.NewConsumerUserWithAnEmailInvitatio" +
                        "nAndCancelTheLinking@pccom.es request received at last-0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
    testRunner.And("1_0 complete consumer user registration (Password:\'Pass123.\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
    testRunner.And("1_0 response is Ok without Errors in the View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
    testRunner.And("1_0 changes the consumer (button:\'Cancelar\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
    testRunner.And("1_0 response is Ok with title (title:\'This user has been registered already. Plea" +
                        "se, go to the login page\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation and link to the consumer", SourceLine=36)]
        public virtual void NewConsumerUserWithAnEmailInvitationAndLinkToTheConsumer()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation and link to the consumer", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationAndLinkToTheConsumer@pccom.es\' Password:\',Adios22\' N" +
                        "ame:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
    testRunner.And("1_0 consumer data is submitted (TradeName:\'El Bar NewConsumerUserWithAnEmailInvit" +
                        "ationAndLinkToTheConsumer\' Address:\'C\\Bajovento 3\' StateOrProvince:\'Alicante\' To" +
                        "wn:\'Elche\' PostalCode:\'03203\' SanitaryMeasures:\'Medida 1, Medida 2\' Image:\'(.*)\'" +
                        ")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table4.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationAndLinkToTheConsumer@pccom.es",
                            "Gon Navarro"});
                table4.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationAndLinkToTheConsumer@pccom.com",
                            "Pepe"});
                table4.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationAndLinkToTheConsumer@pccom.es",
                            "Gonzalo Gallego"});
#line 43
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table4, "Given ");
#line hidden
#line 48
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.NewConsumerUserWithAnEmailInvitatio" +
                        "nAndLinkToTheConsumer@pccom.es request received at last-0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
    testRunner.And("1_0 complete consumer user registration (Password:\'Pass123.\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
    testRunner.And("1_0 response is Ok with title (title:\'WELCOME TO\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
    testRunner.Then("1_0 changes the consumer (button:\'Guardar\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 57
    testRunner.And("1_0 response is Ok with title (title:\'The registration has been completed, please" +
                        " go to the login page\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation and fails because the password must ha" +
            "ve a minimum length of 6", SourceLine=58)]
        public virtual void NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustHaveAMinimumLengthOf6()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation and fails because the password must ha" +
                    "ve a minimum length of 6", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 60
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationAndFailsBecauseThePasswordMustHaveAMinimumLengthOf6@" +
                        "pccom.es\' Password:\',Adios22\' Name:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 61
    testRunner.And(@"1_0 consumer data is submitted (TradeName:'El Bar NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustHaveAMinimumLengthOf6' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'(.*)')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 62
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table5.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustHav" +
                                "eAMinimumLengthOf6@pccom.es",
                            "Gon Navarro"});
                table5.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustHaveA" +
                                "MinimumLengthOf6@pccom.com",
                            "Pepe"});
                table5.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMust" +
                                "HaveAMinimumLengthOf6@pccom.es",
                            "Gonzalo Gallego"});
#line 65
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table5, "Given ");
#line hidden
#line 70
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 71
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.NewConsumerUserWithAnEmailInvitatio" +
                        "nAndFailsBecauseThePasswordMustHaveAMinimumLengthOf6@pccom.es request received a" +
                        "t last-0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
    testRunner.And("1_0 complete consumer user registration (Password:\'passw\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 77
    testRunner.And("1_0 response is Ok with Errors in the View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation and fails because the password must co" +
            "ntain symbols", SourceLine=78)]
        public virtual void NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainSymbols()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation and fails because the password must co" +
                    "ntain symbols", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 80
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainSymbols@pccom.e" +
                        "s\' Password:\',Adios22\' Name:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 81
    testRunner.And(@"1_0 consumer data is submitted (TradeName:'El Bar NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainSymbols' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'(.*)')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table6.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustCon" +
                                "tainSymbols@pccom.es",
                            "Gon Navarro"});
                table6.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustConta" +
                                "inSymbols@pccom.com",
                            "Pepe"});
                table6.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMust" +
                                "ContainSymbols@pccom.es",
                            "Gonzalo Gallego"});
#line 85
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table6, "Given ");
#line hidden
#line 90
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 91
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 92
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 93
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 95
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.NewConsumerUserWithAnEmailInvitatio" +
                        "nAndFailsBecauseThePasswordMustContainSymbols@pccom.es request received at last-" +
                        "0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
    testRunner.And("1_0 complete consumer user registration (Password:\'password\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 97
    testRunner.And("1_0 response is Ok with Errors in the View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation and fails because the password must co" +
            "ntain numbers", SourceLine=98)]
        public virtual void NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainNumbers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation and fails because the password must co" +
                    "ntain numbers", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 100
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainNumbers@pccom.e" +
                        "s\' Password:\',Adios22\' Name:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 101
    testRunner.And(@"1_0 consumer data is submitted (TradeName:'El Bar NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainNumbers' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'(.*)')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 102
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 104
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table7.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustCon" +
                                "tainNumbers@pccom.es",
                            "Gon Navarro"});
                table7.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustConta" +
                                "inNumbers@pccom.com",
                            "Pepe"});
                table7.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMust" +
                                "ContainNumbers@pccom.es",
                            "Gonzalo Gallego"});
#line 105
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table7, "Given ");
#line hidden
#line 110
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 112
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 113
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 114
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 115
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.NewConsumerUserWithAnEmailInvitatio" +
                        "nAndFailsBecauseThePasswordMustContainNumbers@pccom.es request received at last-" +
                        "0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 116
    testRunner.And("1_0 complete consumer user registration (Password:\'password.\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 117
    testRunner.And("1_0 response is Ok with Errors in the View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("New consumer user with an email invitation and fails because the password must co" +
            "ntain uppercase letters", SourceLine=118)]
        public virtual void NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainUppercaseLetters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New consumer user with an email invitation and fails because the password must co" +
                    "ntain uppercase letters", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 119
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 120
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.NewConsu" +
                        "merUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainUppercaseLetter" +
                        "s@pccom.es\' Password:\',Adios22\' Name:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 121
    testRunner.And(@"1_0 consumer data is submitted (TradeName:'El Bar NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustContainUppercaseLetters' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'(.*)')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 122
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 123
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 124
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table8.AddRow(new string[] {
                            "ConsumerUser",
                            "gon.navarro.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustCon" +
                                "tainUppercaseLetters@pccom.es",
                            "Gon Navarro"});
                table8.AddRow(new string[] {
                            "ConsumerUser",
                            "jersiovic.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMustConta" +
                                "inUppercaseLetters@pccom.com",
                            "Pepe"});
                table8.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.NewConsumerUserWithAnEmailInvitationAndFailsBecauseThePasswordMust" +
                                "ContainUppercaseLetters@pccom.es",
                            "Gonzalo Gallego"});
#line 125
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table8, "Given ");
#line hidden
#line 130
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 131
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 132
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 133
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 134
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 135
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.NewConsumerUserWithAnEmailInvitatio" +
                        "nAndFailsBecauseThePasswordMustContainUppercaseLetters@pccom.es request received" +
                        " at last-0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 136
    testRunner.And("1_0 complete consumer user registration (Password:\'password.1\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 137
    testRunner.And("1_0 response is Ok with Errors in the View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("User linked to a consumer that recieves an email invitation and wants to change t" +
            "he consumer wich the user was linked", SourceLine=138)]
        public virtual void UserLinkedToAConsumerThatRecievesAnEmailInvitationAndWantsToChangeTheConsumerWichTheUserWasLinked()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User linked to a consumer that recieves an email invitation and wants to change t" +
                    "he consumer wich the user was linked", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 139
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 140
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga.UserLink" +
                        "edToAConsumerThatRecievesAnEmailInvitationAndWantsToChangeTheConsumerWichTheUser" +
                        "WasLinked@pccom.es\' Password:\',Adios22\' Name:\'Sergio Navarro\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 141
    testRunner.And(@"1_0 consumer data is submitted (TradeName:'El Bar UserLinkedToAConsumerThatRecievesAnEmailInvitationAndWantsToChangeTheConsumerWichTheUserWasLinked' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 142
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 144
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table9.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.UserLinkedToAConsumerThatRecievesAnEmailInvitationAndWantsToChange" +
                                "TheConsumerWichTheUserWasLinked@pccom.es",
                            "Gonzalo Gallego"});
#line 145
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table9, "Given ");
#line hidden
#line 148
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 149
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 150
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 151
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 152
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 153
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.UserLinkedToAConsumerThatRecievesAn" +
                        "EmailInvitationAndWantsToChangeTheConsumerWichTheUserWasLinked@pccom.es request " +
                        "received at last-0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 154
    testRunner.And("1_0 complete consumer user registration (Password:\'Password.1\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 155
    testRunner.And("1_0 response is Ok with title (title:\'WELCOME TO El Bar\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 156
     testRunner.Then("1_0 changes the consumer (button:\'Guardar\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 157
    testRunner.And("1_0 response is Ok with title (title:\'The registration has been completed, please" +
                        " go to the login page\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 159
    testRunner.Given("1_0 a new user confirmed with (Type:\'ConsumerUser\' UserEmail:\'raulaliaga2.UserLin" +
                        "kedToAConsumerThatRecievesAnEmailInvitationAndWantsToChangeTheConsumerWichTheUse" +
                        "rWasLinked@pccom.es\' Password:\',Adios22\' Name:\'Pepe\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 160
    testRunner.And(@"1_0 consumer data is submitted (TradeName:'El Bar UserLinkedToAConsumerThatRecievesAnEmailInvitationAndWantsToChangeTheConsumerWichTheUserWasLinked' Address:'C\Bajovento 3' StateOrProvince:'Alicante' Town:'Elche' PostalCode:'03203' SanitaryMeasures:'Medida 1, Medida 2' Image:'')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 161
    testRunner.Then("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 162
    testRunner.And("1_0 get access token from refresh token to get updated claims", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 163
    testRunner.And("1_0 start using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Email",
                            "Name"});
                table10.AddRow(new string[] {
                            "ConsumerUser",
                            "gonzalogallego.UserLinkedToAConsumerThatRecievesAnEmailInvitationAndWantsToChange" +
                                "TheConsumerWichTheUserWasLinked@pccom.es",
                            "Gonzalo Gallego"});
#line 164
    testRunner.Given("1_0 send new consumer user invitation", ((string)(null)), table10, "Given ");
#line hidden
#line 167
    testRunner.And("1_0 response is Created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 168
    testRunner.And("1_0 stop using access token for all requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 169
    testRunner.And("1_0 reset client cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 170
    testRunner.Then("1_0 invitation created contains valid consumerId", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 171
    testRunner.And("1_0 store last consumer user invitations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 172
    testRunner.Then("1_0 confirm user invitation to gonzalogallego.UserLinkedToAConsumerThatRecievesAn" +
                        "EmailInvitationAndWantsToChangeTheConsumerWichTheUserWasLinked@pccom.es request " +
                        "received at last-0 user email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 173
    testRunner.And("1_0 response is Ok and shows LoginPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 174
    testRunner.When("1_0 user login with username and password (Password:\'Password.1\' UserName:\'gonzal" +
                        "ogallego.UserLinkedToAConsumerThatRecievesAnEmailInvitationAndWantsToChangeTheCo" +
                        "nsumerWichTheUserWasLinked\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 175
    testRunner.And("1_0 changes the consumer (button:\'Guardar\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 176
    testRunner.Then("1_0 response is Ok with title (title:\'The registration has been completed, please" +
                        " go to the login page\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
