export const LOCATIONS_SEARCH_BY_WORD = "LOCATIONS_SEARCH_BY_WORD"
export const LOCATIONS_RELOAD_DATA = "LOCATIONS_RELOAD_DATA"
export const LOCATIONS_RELOAD_DISPLAY_DATA = "LOCATIONS_RELOAD_DISPLAY_DATA"