const STRINGS = {
  formData: 'multipart/form-data',
  appFormEncoded: 'application/x-www-form-urlencoded',
  appJson: 'application/json',
  GET: 'get',
  PUT: 'put',
  POST: 'post',
  DELETE: 'delete',
  provider: 'provider',
  location: 'location',
  weekday: 'weekday',
  google: 'Google',
  login: 'login',
  registration: 'registration',
  addNewLocation: 'Añadir Nuevo Lugar',
  addToMyProduct: 'Añadir a Mis Productos',
  removeFromMyProducts: 'Eliminar de Mis Productos',
  saveProduct: 'Guardar Cambios',
  all: 'TODOS',
  pending: 'PENDIENTES',
  employee: 'employee',
  admin: 'admin',
  name: 'name',
  saveProductCarte: 'Guardar Cambios',
  removeFromMyProductsCarte:'Eliminar de Mis Productos',
  addNewSection: 'Añadir Nueva Sección',
  addToMyProductCarte: 'Añadir a Mis Productos',
  section: 'section',
};

export { STRINGS };
